name: Build

on:
  push:
    branches:
      - advanced-features
  pull_request:
    branches:
      - advanced-features

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Specify the Flutter version you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test